@startuml BookAggregation

title 書籍集約（Book Aggregation）

package "書籍集約（BookAggregation）" {
    ' 1. エンティティの定義
    class "Book(書籍)" as Book << (R, red) RootEntity >> {
        BookId: BookId
        Title: タイトル
        Price: 価格
    }

    class "Stock(在庫)" as Stock << (E, green) Entity >> {
        StockId: StockId
        QuantityAvailable: 在庫数
        Status: ステータス
    }

    ' 2. 属性の定義
    class "BookId" as BookId {
        + value: string
    }

    class "Title(タイトル)" as Title {
        + value: string
    }

    class "Price(価格)" as Price {
        + value: number
    }

    class "Status(ステータス)" as Status {
        + value: Enum { InStock, LowStock, OutOfStock }
    }

    class "StockId" as StockId {
        + value: string
    }

    class "QuantityAvailable(在庫数)" as QuantityAvailable {
        + value: number
    }

    ' 3. ルールの追加
    note bottom of BookId
        ISBNコードを適用する。
        ISBNコードは、ISBNのあとに数字で「978」、
        さらにグループ（国・地域）番号（日本は4）、出版社番号、書名番号、の合計12桁の数字を並べ、
        最後にこの12桁の数字を特定の計算式で演算して得た1桁のチェック用の数を付け加えたコード。
    end note

    note bottom of Title
        MAX_LENGTH = 1000
        MIN_LENGTH = 1
    end note

    note bottom of QuantityAvailable
        MAX = 1,000,000
        MIN = 1
    end note

    note bottom of Price
        日本円のみ扱う。
        MAX = 1,000,000
        MIN = 1
    end note

    note bottom of Stock
        - 初回作成時、ステータスは「在庫切れ」から始まる。
        - 在庫数は0の場合は在庫切れ。10以下の場合は残りわずか。それ以外は在庫あり。
    end note

    note bottom of Status
        在庫のステータスは、 InStock (在庫あり), LowStock (残りわずか),
        OutOfStock (在庫切れ)の3つ
    end note

    ' 4. 関連性の定義
    Book "1" -down- "1" Stock : has >

    Book *-down- BookId
    Book *-down- Title
    Book *-down- Price

    Stock *-down- StockId
    Stock *-down- QuantityAvailable
    Stock *-down- Status
}

@enduml
